# Generated by Django 3.2 on 2022-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='users/%Y/')),
                ('wallet', models.PositiveBigIntegerField(default=0)),
                ('state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('plate', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
