# Generated by Django 3.2 on 2022-04-10 05:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('body', models.TextField(blank=True, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('price', models.BigIntegerField(default=0)),
                ('price_after_discount', models.BigIntegerField(default=0)),
                ('company_price', models.BigIntegerField(default=0)),
                ('manufacturer_company', models.CharField(blank=True, max_length=120, null=True)),
                ('repository_quantity', models.PositiveBigIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='products', to='categories.Category')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
