# Generated by Django 3.2 on 2022-04-10 06:53

from django.db import migrations, models
import django.db.models.deletion
import threed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=threed.models.uip1)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=threed.models.uip2)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=threed.models.uip3)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=threed.models.uip4)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=threed.models.uip5)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=threed.models.uip6)),
                ('image7', models.ImageField(blank=True, null=True, upload_to=threed.models.uip7)),
                ('image8', models.ImageField(blank=True, null=True, upload_to=threed.models.uip8)),
                ('image9', models.ImageField(blank=True, null=True, upload_to=threed.models.uip9)),
                ('image10', models.ImageField(blank=True, null=True, upload_to=threed.models.uip10)),
                ('image11', models.ImageField(blank=True, null=True, upload_to=threed.models.uip11)),
                ('image12', models.ImageField(blank=True, null=True, upload_to=threed.models.uip12)),
                ('image13', models.ImageField(blank=True, null=True, upload_to=threed.models.uip13)),
                ('image14', models.ImageField(blank=True, null=True, upload_to=threed.models.uip14)),
                ('image15', models.ImageField(blank=True, null=True, upload_to=threed.models.uip15)),
                ('image16', models.ImageField(blank=True, null=True, upload_to=threed.models.uip16)),
                ('image17', models.ImageField(blank=True, null=True, upload_to=threed.models.uip17)),
                ('image18', models.ImageField(blank=True, null=True, upload_to=threed.models.uip18)),
                ('image19', models.ImageField(blank=True, null=True, upload_to=threed.models.uip19)),
                ('image20', models.ImageField(blank=True, null=True, upload_to=threed.models.uip20)),
                ('image21', models.ImageField(blank=True, null=True, upload_to=threed.models.uip21)),
                ('image22', models.ImageField(blank=True, null=True, upload_to=threed.models.uip22)),
                ('image23', models.ImageField(blank=True, null=True, upload_to=threed.models.uip23)),
                ('image24', models.ImageField(blank=True, null=True, upload_to=threed.models.uip24)),
                ('image25', models.ImageField(blank=True, null=True, upload_to=threed.models.uip25)),
                ('image26', models.ImageField(blank=True, null=True, upload_to=threed.models.uip26)),
                ('image27', models.ImageField(blank=True, null=True, upload_to=threed.models.uip27)),
                ('image28', models.ImageField(blank=True, null=True, upload_to=threed.models.uip28)),
                ('image29', models.ImageField(blank=True, null=True, upload_to=threed.models.uip29)),
                ('image30', models.ImageField(blank=True, null=True, upload_to=threed.models.uip30)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='products.product')),
            ],
        ),
    ]
