# Generated by Django 3.2 on 2022-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitems_refundordersrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
