# Generated by Django 3.2 on 2022-04-21 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitems_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
