# Generated by Django 3.2 on 2022-05-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundordersrequest',
            options={'ordering': ('-id',)},
        ),
    ]
